Image prune policy
- keep 3 last pulled/pushed images
- keep pulled and pushed images for 30d
- blob gc delay >24h to allow cheap regsync in case pruning and regsync conflict
- separate prefetch-image from zot to simplify deployment
- use kustomize for managing zot config (= automatic deployment update)
- regsync: don't recreate index if already existing

diff --git a/zot/regsync/regsync-cronjob.yaml b/zot/regsync/regsync-cronjob.yaml
--- a/zot/regsync/regsync-cronjob.yaml
+++ b/zot/regsync/regsync-cronjob.yaml
@@ -26,10 +26,14 @@ spec:
                 regsync ${regsynccmd} --config /etc/regsync/config.yaml --logopt json 2> >(tee -a /regsync.log >&2) || true
                 FIXIDX=$(cat /regsync.log | grep -e '^{"time":' | jq -rs '[.[]|select(.msg=="Image sync needed" and (.target|test("/stephanme/")|not))|.target]|join(" ")')
                 regctl registry set --tls=disabled registry.fritz.box
+                echo "Fix missing index manifests"
                 for target in $FIXIDX; do
-                  echo regctl index create $target --platform linux/amd64 --platform linux/arm64 --platform unknown/unknown --ref ${target:19}
-                  if [ "$regsynccmd" = "once" ]; then
-                    regctl index create $target --platform linux/amd64 --platform linux/arm64 --platform unknown/unknown --ref ${target:19}
+                  regctl manifest head $target > /dev/null
+                  if [ $? -ne 0 ]; then
+                    echo regctl index create $target --platform linux/amd64 --platform linux/arm64 --platform unknown/unknown --ref ${target:19}
+                    if [ "$regsynccmd" = "once" ]; then
+                      regctl index create $target --platform linux/amd64 --platform linux/arm64 --platform unknown/unknown --ref ${target:19}
+                    fi
                   fi
                 done
               volumeMounts:
